do_build.sh

- Fix the OE download path in sync_cache*
- rsync doesn't need to run as root
- When running sync_cache_back, we want to exclude the clones of our own repositories, otherwise subsequent builds that run sync_cache will use old versions of the repos. I fixed the rsync exclude rule so that it doesn't sync back any path that contains the word "OpenXT" or "openxt". If you use local clones, make sure they have that word in their path!
- We used to tag the repositories before building, and use that tag as a build "branch". We don't want that anymore, builds should be able to have an ID and work on a normal branch.
Singed-off-by: Jed Lejosne <jed.openxt@gmail.com>

[do_build.sh] fix some legacy stuffs

---

do_build.sh

Seems to be cruft from old XenClient days. If using low numbers as ID, this would result in negative numbers in the version string.

Remove arbitrary 'ID - 110000' math from tools version string

---

example-config

Since it was created and is more readily maintained, use the
mirror.openxt.org site.

Change mirror in example to mirror.openxt.org

---

do_build.sh

Client doesn't rely on sync-wui, so build should not fail if this wasn't
built.

Remove dependency on sync-wui build

---

windows/config/sample-config.xml

Added signtool path parameter to initial sample-config.xml to be passed on
to powershell scripts.  The installer was failing to get signed correctly because of this.

[OXT-105] Added parameters which get passed down to powershell scripts for signtool.

---

do_build.sh

To ease readability and alignment, replaced instances of tab character
with 8 spaces to be consistent with the majority of the file.
TODO: normalize indents to either tabstop of 2 or 4 after to reduce
massive indents.

Normalized tabs to spaces in do_build.sh

---

do_build.sh

Added shorthand ACM for Broadwell (bdw) to list
OXT-126

Broadwell ACM/SINIT Integration

---

manifest

manifest: make syncvm optional, as OpenXT should run just fine without it

---

build/conf/local.conf-dist

Prefer to use the libc headers matching kernel version.
This was likely forgotten during the upgrade to Linux 3.18.

[conf] libc headers matching kernel.

---

windows/winbuild-prepare.ps1

Corrects C:\Program Files to C:\Program Files (x86) when building on a 64-bit system.

Fix path to windows sign tool on x64.

---

build/conf/local.conf-dist

Use the DISTRO=openxt-main instead (see relevant commit in
xenclient-oe.git).
See https://github.com/OpenXT/xenclient-oe/pull/181 for related changes in xenclient layer (xenclient-oe.git).

Remove recipes versions from local.conf

---

.gitignore

Ensures config doesn't sneak into commits, and also prevents accidental
deletion via 'git clean'

Add .config to gitignore

---

.gitignore
build/conf/bblayers.conf
build/conf/local.conf-dist
do_build.sh
example-config
setup_build-next.sh

These changes are for building the xenclient-oe repo against the current OE Jethro (2.0) release.  Make sure to use a new or updated build host/container.  See  https://openxt.atlassian.net/wiki/display/BS/Jessie+systemd+container for instructions on creating a new Jessie systemd container.

Jethro merge

---

example-config

Using meta-selinux branch master as of this day will conflict with
oe-core jethro branch:
ERROR: No recipes available for
meta-selinux/recipes-extended/findutils/findutils_4.6.%.bbappend
meta-selinux/recipes-devtools/e2fsprogs/e2fsprogs_git.bbappend
Propositions to manage multiple layers configuration are already
discussed. Until that is done, resort to pick a fixed, compatible, rev.

Clone meta-selinux at known good rev.

---

build/conf/local.conf-dist

The problem is that there are a small number of unlabeled files in the final
image produced by gene3fs, whereas building the filesystem images using the
normal tools does not exhibit this problem.  It turns out that these are
cases where there were multiple hard links to a single file (e.g. e2fsck,
fsck.ext2, fsck.ext3, fsck.ext4).  In the pseudo files database, only one of
the instances is getting its attribute recorded, and in the filesystem image
that is generated by gene3fs, multiple hard links to the same inode are not
being preserved; multiple separate inodes are being created and the other
instances are never getting an xattr set.  In contrast, mkfs.ext3 preserves
the hard links as links and correctly labels the inode.
In the old pseudo xattr patch in openxt, xattrs were fetched by …

Drop usage of gene3fs.

---

build-scripts/build.sh
build-scripts/centos/setup.sh
build-scripts/debian/setup.sh
build-scripts/oe/build.sh
build-scripts/oe/setup.sh
build-scripts/setup.sh

These commits allow the name of the build user to be configured, and adds lines to the ssh configuration to make things simpler for the user (example: `ssh oe` will take you to the oe container)

Custom build username and easy ssh

---

build-scripts/setup.sh

Because that's what the other scripts do.

build-scripts: make the main ssh key a dsa one

---

build-scripts/oe/setup.sh

The old package we manually download just got removed from the main Debian repos and can only be found in archive.debian.org.

build-scripts: move to Debian Archive for the old gmp packages

---

windows/PackageLibrary.psm1
windows/PerformDownload.psm1

- Install GPG
- Use GPG instead of a hash (that keeps changing) to verify the Cygwin installer
- Fix the 7-zip URL

windows: mkbuildmachine: improvements

---

windows/PackageLibrary.psm1
windows/PerformDownload.psm1

CAPICOM was most likely needed only for Windows XP build machines.
The link is broken and I got a successful build without it.

windows: mkbuildmachine: remove CAPICOM and trailing whitespace

---

windows/BuildDaemon/winbuildd.bat
windows/BuildDaemon/winbuildd.ps1

winbuildd.bat goes to the startup folder
winbuildd.ps1 is used by winbuildd.bat to start the daemon as Administrator
OXT-507

windows build daemon: add startup scripts

---

example-config

commit 096a5ee ("Clone meta-selinux at known good rev.") switched
meta-selinux to using a specific commit because at the time,
meta-selinux had no jethro branch and changes in the master branch
broke the build.  Since that time, Phil created a jethro branch for
meta-selinux, so we can switch back to letting meta-selinux default
to following OE_BRANCH.   In this manner, we ensure that any subsequent
jethro-compatible fixes and improvements to meta-selinux will be picked up
by future OpenXT builds.
Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>

Allow meta-selinux to follow the jethro branch.

---

build-scripts/build.sh
build-scripts/fetch.sh
build-scripts/setup.sh

This allows users to fetch the git repos and/or restart the git service after a host reboot, without starting a whole new build.
OXT-507

build-scripts: move the git build bits to their own script

---

build-scripts/build.sh

build-scripts: add check to cleanly not build non-existent containers/VMs

---

build-scripts/centos/build.sh

build-scripts: centos: use the simpler notation for the oracle scp instructions

---

do_build.sh

In addition to the use of a local .config or environment specification of a CONFIG variable, add a '-c <PATH>' option.
Also, relocated the parsing of config to after the parsing of command arguments to support this mode.

Added command-line specification of config

---

do_build.sh

netboot directory needs a copy of the license alongside binaries
and so do copies of the installer directories.

OXT-588: include ACM software license with binary files

---

build-scripts/setup.sh

Add additional packages that are required for a working environment
and removed duplicate packages from list.
Signed-off-by: Daniel P. Smith <dpsmith@apertussolutions.com>
(cherry picked from commit 1c4a801fe8aa4c856a4041aa28ddfff54db0cc55)
Conflicts:
build-scripts/setup.sh

STABLE-6: build-scripts: cleanup package install

---

build-scripts/build.sh
build-scripts/oe/build.sh
build/conf/bblayers.conf
do_build.sh
do_installer_iso.sh
example-config
setup_build-next.sh

Add meta-intel to the layers used in OpenXT in order to provide upstream tools to manage Intel microcode.
Amend the deployment scripts (do_build.sh and do_installer_iso.sh) to ship the microcode update with the installer so Xen can perform the update when booting on OpenXT installer.
Last commit add a change to genisoimage and what standard is enforced for file names in OpenXT ISO images to avoid mangling names more than 8 characters + '.' + up to 3 characters long.
OXT-709

OXT-709: Add meta-intel layer to the bblayout and amend deployment scripts

---

.gitmodules
build-scripts/oe/build.sh

Typo due to renaming for ISO9660 consistency.
Add meta-intel to the git submodules.

OXT-743: Fix microcode changes for build-scripts

---

build-scripts/oe/build.sh

Correct the shell variable expansion to allow iteration through
all images in a layer.

OXT-507: partial build fix: unbreak iteration over layer contents

---

build-scripts/build.sh
build-scripts/oe/build.sh

Argument is only used in the OE build in this initial version.
Configures BB_NUMBER_THREADS and PARALLEL_MAKE variables.
Supports adjusting the value when continuing an existing build.

[build scripts] add -j command option to specify build concurrency

---

build/conf/local.conf-dist

Fetch from cdn.kernel.org
wget < 1.12 or 1.13 has trouble fetching from www.kernel.org since it
allows only use of TLS (so squeeze/wheezy containers might have issue
downloading kernel tarballs).
Nevertheless, it seems we should fetch from cdn.kernel.org anyway.
https://www.kernel.org/introducing-fastly-cdn.html

STABLE-5: Change kernel.org mirror.

---

example-config

Done for openembedded-core.git and meta-openembedded.git; meta-selinux.git
did not change and meta-java.git has not jethro branch so it was left as is.
OXT-851

STABLE-6: Move Jethro branch revisions to latest.

---

build-scripts/debian/build.sh

build-scripts: debian: rename directories before building to silence warnings

---

build-scripts/debian/setup.sh

build-scripts: debian: setup.sh: add missing package in chroots

---

version

[upgrade] Since 6.0.0 does not support wildcards, add it explicitly.

---

do_build.sh

STABLE-6: Have to add KBL to do_build.sh too in 6.x.

---

do_build.sh
example-config
setup_build
setup_build-next.sh

do_build is deprecated, it is recommended to use the build-scripts. Yet some people might still have setups using the legacy script.

do_build.sh: Add meta-virtualization layer handling.

---

build-scripts/build.sh

Fixes a usability annoyance that becomes apparent with frequent use of the build script with interrupted builds.

[build scripts] Skip mirror fetch when continuing an existing build

---

build-scripts/debian/setup.sh

Add dh-autoreconf to debian container and in chroot environment to build
libv4v (or any autotool package for that matter).
I could not get sbuild to install dh-autoreconf from the ```Build-Depends:``` in ```debian/control``` from libv4v.
OXT-978

OXT-978: build-scripts: Add dh-autoreconf dependency.

---

do_build.sh

This is needed for the new build server to configure opkg correctly, since it doesn't match the hardcoded URI layout.

STABLE-6: do_build.sh: make XENCLIENT_PACKAGE_FEED_URI configurable

---

build/conf/local.conf-dist

Using the new build scripts, there's no way to specify how many threads we want to build OpenXT.
The default, 4, seems really weak, 8 should make more sense on most build machines.
This PR is very low priority, do not bother cutting a new 6.0.1 RC just for that.

STABLE-6: local.conf-dist: hardcode 8 threads instead of 4

---

build/conf/local.conf-dist

PRs for: xenclient-oe, openxt and meta-openxt-ocaml-platform.
Export OCaml variables for the ocaml findlib wrapper.

OXT-1016: Only build the Xen recipes once per build

---

common-config

See release notes:
https://www.xenproject.org/downloads/xen-archives/xen-46-series/xen-466.html
Depends on: https://github.com/OpenXT/xenclient-oe/pull/724

OXT-1187: xen: upgrade to 4.6.6

---

common-config

[Xen 4.9] Update Xen hypervisor and tools to latest major release 4.9.0

---

build/conf/local.conf-dist

hs-vhd recipe is building the same utility as the Hackage vhd package
used for other depdencies. This is not required.

OXT-1213: conf: hs-vhd is redundant.

---

build-scripts/setup.sh

We create a bridge named \<user\>br0, and bridge names have to be shorter than 16 characters.

build-scripts: limit build user to less than 13 characters

---

common-config

Update to the latest Xen 4.9.1 release.
OXT-1256
Requires https://github.com/OpenXT/xenclient-oe/pull/810

OXT-1256: xen: 4.9.1 Uprev

---

build/conf/local.conf-dist

This is now defined in meta-openxt-ocaml-layer under the findlib.bbclass and ocaml.bbclass.
This was forgotten in the original set of PRs and is no longer required.

OXT-1253: ocaml: Align with layer refactorisation.

---

build-scripts/20-xenclient-oe.layer
build-scripts/build.sh
build-scripts/oe/build.sh
build-scripts/oe/setup.sh
build-scripts/setup.sh
do_build.sh
do_installer_iso.sh

This PR includes the changes necessary for building OpenXT with UEFI support. The two major changes are the splitting of the `openxt-installer` into its own machine type and using `xorriso` to build an ISO image bootable both under legacy and UEFI.
Related PRs:
https://github.com/OpenXT/xenclient-oe/pull/828
https://github.com/OpenXT/installer/pull/63

OXT-1280: UEFI support

---

.gitmodules
build-scripts/20-xenclient-oe.layer
build-scripts/build.sh
build-scripts/oe/build.sh
build-scripts/oe/setup.sh
build/conf/bblayers.conf
build/conf/local.conf-dist
do_build.sh
example-config
manifest
setup_build
setup_build-next.sh

Update the build configuration to handle the Bitbake/OE upgrade.
The biggest change to any downstream is the relocation of some configuration previously done in the local.conf-dist file to the xenclient-oe layer.
- It is recommended to move `PREFERRED_*` configuration to the distro configuration (see [openxt-main.conf](https://github.com/OpenXT/xenclient-oe/blob/master/conf/distro/openxt-main.conf) for example),
- `debug-tweaks` in `IMAGE_FEATURE` is extended by the layer,
- `source-image` is deprecated and removed,
- `FILESYSTEM_PERMS_TABLES` is set at the distro level,
- Images format are no longer prefixed with `.xc` as it is no longer necessary.
- buildstats are no longer collected by the build-scripts, bitbake and provided tools can be used directly.
See …

OXT-880: OE upgrade to pyro

---

.gitmodules

OpenXT compilation issues with gcc 6.4 have been fixed.
Also refresh submodules (which is done automatically by build.sh otherwise).

oe-core: Use tip of pyro.

---

build-scripts/build.sh
build-scripts/oe/setup.sh
do_build.sh

fuse doesn't play nicely in a container environment since it wants to
load modules and do other privileged operations.  Instead use mtools
which can just be run as the user.
OXT-1280
I only tested the do_build.sh changes since I don't use the build-scripts/build.sh setup.  But I made the changes to keep the two implementations in sync.

do_build.sh: Use mtools instead of fuse for UEFI

---

build-scripts/build.sh
build-scripts/oe/setup.sh
do_build.sh

fuse doesn't play nicely in a container environment since it wants to
load modules and do other privileged operations.  Instead use mtools
which can just be run as the user.
OXT-1280
(cherry picked from commit 9642a3244d90068f6c311c539054a87af009c28f)

STABLE-8: do_build.sh: Use mtools instead of fuse for UEFI

---

build-scripts/oe/setup.sh

To help enforce consistency with the OpenXT patch format, install a
.quiltrc file for the build container user.
This is untested.  How does it look, @jean-edouard ?  I would have preferred just copying a file into place, but since we are executed by streaming the script over ssh, this will have to do.

oe/setup.sh: Create .quiltrc in OE build container

---

build-scripts/build.sh

setup.sh does not setup a Windows VM by default,
so build.sh should not assume there is one.
OXT-507

build.sh: do not assume there is a Windows VM

---

build-scripts/build.sh

setup.sh does not setup a Windows VM by default,
so build.sh should not assume there is one.
OXT-507
(cherry picked from commit 8ead1492f45b047fe6dfcabac3b0a205a19cbaa9)

STABLE-8: build.sh: do not assume there is a Windows VM

---

build-scripts/debian/install.sh

Signed-off-by: Jafar Al-Gharaibeh <jafar@atcorp.com>

build-scripts: openxt prefix was dropped from the v4v deb package name

---

build-scripts/debian/install.sh

Signed-off-by: Jafar Al-Gharaibeh <jafar@atcorp.com>

STABLE-8: build-scripts: openxt prefix was dropped from the v4v deb package name

---

do_build.sh

This is the stable-8 version of https://github.com/OpenXT/openxt/pull/312
The Coffee Lake ACM is needed otherwise isolinux fails to boot because
it cannot find the cfl.acm file.
OXT-1310
(cherry picked from commit 1d18021ac1a16298dfb76e726383302b1264693d)

STABLE-8: OXT-1310: do_build.sh: Add Coffee Lake ACM

---

build-scripts/debian/install.sh

Add source as trusted before install to allow install without disabling apt source signing.
Tested on Ubuntu 18.04

Openxt client tool install signing for 18.04+

---

build-scripts/debian/install.sh

From [master #315 ](https://github.com/OpenXT/openxt/pull/315)
Add source as trusted before install to allow install without disabling apt source signing.
Tested on Ubuntu 18.04

STABLE-8: Openxt client tool install signing for 18.04+

---

do_build.sh

This fixes the syntax error aborting the script:
"./do_build.sh: line 37: syntax error near unexpected token `fi'"
OXT-1346

do_build: Fix bash syntax

---

build-scripts/oe/build.sh
common-config
do_build.sh
pkg-xctools/build.sh
pkg-xctools/control/control
pkg-xctools/control/postinst

xen-common.inc is directly using these variables, it should be easier to
handle everything from the same place.
- https://github.com/OpenXT/xenclient-oe/pull/1012

OXT-1346: xen: Move version management to the recipes.

---

build-scripts/setup.sh

Change the way Debian is identified to a more common approach (also works for RHEL and other distros). Also, lxc 3.0 doesn't like the legacy config options that are manually added by the setup tools, but seems to be happy after an lxc-update-config which saves a bit of work handling lxc versions manually.

Ubuntu build support - setup script

---

build/conf/local.conf-dist

This source has proven itself to be quite volatile. Provide default
convenience fallback to avoid frustration when building a clean tree.

OXT-1410: conf: Add seabios SRC_URI usual MIRROR

---

build/conf/local.conf-dist

This source has proven itself to be quite volatile. Provide default
convenience fallback to avoid frustration when building a clean tree.
(cherry picked from commit c0050df251d7738d37cdb473d822db2da43f369f)

STABLE-8: OXT-1410: conf: Add seabios SRC_URI usual MIRROR

---

build-scripts/debian/install.sh

The kernel headers are automatically installed as a dkms dependency.
However, apt will install the headers for the latest kernel, which
is not necessarily the current kernel, especially if the user
didn't dist-upgrade as recommended.

debian install script: ensure current kernel headers are installed

---

build-scripts/build.sh

OE takes 3 hours to build, Centos Debian and Windows each take about 5 minutes.
However, those last 3 are about as likely to fail as OE, maybe even more so for Windows.
In an attempt to fail as fast as possible, build:
- Windows first, that randomly breaks, especially around monthly updates
- Centos second, since the container tends to fail to start after builder reboots
- Debian third, less likely to break but really quick
- OE last, since it's the longest step

build-scripts: reverse build order

---

build-scripts/debian/install.sh

Debian variants like Devuan may not have that file.
OXT-1470

debian_install.sh: do not fail when /etc/debian_version doesn't exist

---

build-scripts/debian/install.sh

Debian variants like Devuan may not have that file.
OXT-1470
(cherry picked from commit b32d338c61bc6e6c5a3da0b00ac12ee1a73aab39)

STABLE-8: debian_install.sh: do not fail when /etc/debian_version doesn't exist

---

build-scripts/oe/build.sh
do_build.sh

grubx64.efi is a convenience symlink to grub-efi-bootx64.efi.
Unfortunately, it can get set to grub-efi-bootia32.efi if
grub-efi-native:do_deploy runs after grub-efi.  This breaks the build
with
cp: cannot stat ‘tmp-glibc/deploy/images/openxt-installer/grubx64.efi’: No such file or directory
Just copy the actual file and avoid the symlink.
OXT-1484
I tested the do_build code path, but I don't have a build-scripts setup to test that one.

Stop using grubx64.efi symlink

---

.gitmodules

The meta-selinux layer doesn't have a pyro branch, so we were following master.
But master aligns with the OE/Yocto master branches, not pyro.
As master diverges, the probability of new changes breaking OpenXT increases.
This is what just happened.
This freezes the layer to prevent that from happening again.

meta-selinux: freeze layer to latest safe commit

---

build-scripts/oe/build.sh
do_build.sh

grubx64.efi is a convenience symlink to grub-efi-bootx64.efi.
Unfortunately, it can get set to grub-efi-bootia32.efi if
grub-efi-native:do_deploy runs after grub-efi.  This breaks the build
with
cp: cannot stat ‘tmp-glibc/deploy/images/openxt-installer/grubx64.efi’: No such file or directory
Just copy the actual file and avoid the symlink.
OXT-1484
(cherry picked from commit b4dc32d8da0442cdb06f437c9d8a81f1bad38b19)

Stable-8: OXT-1484: Stop using grubx64.efi symlink

---

build-scripts/oe/setup.sh
build-scripts/setup.sh

x86_64: OpenXT base repo changes

---

build-scripts/debian/setup.sh

Debian Wheezy has been removed from standard Debian mirrors.
It now lives in archive.debian.org.
Forcing it fixes setup.sh.

build-scripts: debian setup: force archive mirror for Wheezy

---

do_build.sh

Drop sysroot from the script.  It's unneeded and unused as far as I can tell.  I usually drop syncui,source,sdk,license,sourceinfo as well, but I've left those.
Re-order sourcing the .config file before parsing the command line options.  This way you can set your common variables in .config and override on the command line.  The current way does not allow command line overriding.  For instance, you can set your default STEPS in .config, but then run just `./do_build.sh -s ndvm,ship` to do a quicker partial re-build.
Third, print the date when finished.  I find this useful when I have multiple windows open to know when a build last finished.

do_build.sh improvements

---

do_build.sh

This is the Stable-9 version of https://github.com/OpenXT/openxt/pull/342
Drop sysroot from the script. It's unneeded and unused as far as I can tell. I usually drop syncui,source,sdk,license,sourceinfo as well, but I've left those.
Re-order sourcing the .config file before parsing the command line options. This way you can set your common variables in .config and override on the command line. The current way does not allow command line overriding. For instance, you can set your default STEPS in .config, but then run just ./do_build.sh -s ndvm,ship to do a quicker partial re-build.
Third, print the date when finished. I find this useful when I have multiple windows open to know when a build last finished.

STABLE-9: do_build.sh improvements

---

version

8.0.1 has been versioned 8.0.0.
Add upgrade path from the latest released version.

S9: OXT-1611: version: Allow upgrades from 8.0.0.

---

build-scripts/centos/install.sh
build-scripts/debian/install.sh

Build and ship them but don't install them by default, since OpenXT uses argo now.
They can still be installed manually with apt-get/yum if needed.

build-scripts: linux install: skip the v4v packages

---

build-scripts/centos/install.sh
build-scripts/debian/install.sh

Build and ship them but don't install them by default, since OpenXT uses argo now.
They can still be installed manually with apt-get/yum if needed.
(cherry picked from commit 2510add92751cbb99c1e74417a2a318293bb72ef)

S9: build-scripts: linux install: skip the v4v packages

---

build-scripts/debian/install.sh

The xenmou driver causes issues on Debian and Ubuntu
systems. Debian systems will boot without mouse
functionality and Ubuntu systems won't make it to the
login screen due to a dereferenced NULL pointer.
Note that this is a temporary bandaid and should be
fixed when possible.
OXT-1608
Signed-off-by: Nicholas Tsirakis <tsirakisn@ainfosec.com>

[debian] Temporary: Don't install xenmou driver

---

build-scripts/debian/install.sh

The xenmou driver causes issues on Debian and Ubuntu
systems. Debian systems will boot without mouse
functionality and Ubuntu systems won't make it to the
login screen due to a dereferenced NULL pointer.
Note that this is a temporary bandaid and should be
fixed when possible.
OXT-1608
Signed-off-by: Nicholas Tsirakis <tsirakisn@ainfosec.com>

S9: [debian] Temporary: Don't install xenmou driver

---

version

OpenXT policy is to allow upgrades from the last major, latest
micro-release. Replace 9.0.0 with 9.0.1.

version: Allow upgrade from upcoming release.

---

build-scripts/fetch.sh

All the OpenXT repositories are mirrored in /home/git, but some may
not have the branch we're currently building, which is usually ok.
Log the missing branch and keep going instead of erroring out.

build-scripts: fetch.sh: keep going when a branch is missing

---

build-scripts/fetch.sh

All the OpenXT repositories are mirrored in /home/git, but some may
not have the branch we're currently building, which is usually ok.
Log the missing branch and keep going instead of erroring out.
(cherry picked from commit 36083e1b7191548d05106575eebf0a940de107ba)

S9: build-scripts: fetch.sh: keep going when a branch is missing

---

build-scripts/windows/setup.sh
windows/mkbuildserver.ps1

virt-install is now (as of Debian Buster) stricter about VM options.
Added the missing params to make it happy.
Also the latest Windows 10 rejects "''" for the empty string argument
of ssh-keygen, and expects '""' instead, which actually makes sense.

Fix Windows build machine setup on recent versions

---

build-scripts/oe/setup.sh
build-scripts/setup.sh

Also add explicit install of libncursesw5, which doesn't seem to
get pulled automatically anymore in Buster.

build-scripts: setup.sh: Update the OE container to Debian Buster

---

.gitmodules

OpenXT master currently aligns on Zeus.
meta-java provides a zeus branch, so it should be tracked instead of
master.
OpenXT master builds are currently broken as `meta-java` `master` is no longer compatible with `zeus` since, at least,  `openembedded-core/meta/classes/distro_features_check.bbclass` is deprecated in favor of `openembedded-core/meta/classes/features_check.bbclass`.

modules: Track meta-java zeus branch

---

build-scripts/build.sh
build-scripts/oe/build.sh

With the removal of IMAGE_POSTPROCESS_COMMAND for xenclient-installer-image, the ISO and PXE files end up in slightly different directories.
The postprocess commands were able to use IMAGE_LINK_NAME to create a subdirectory, which is not possible in do_deploy.
- https://github.com/OpenXT/xenclient-oe/pull/1341

build: handle do_deploy refactoring

---

do_build.sh

This updates do_build.sh to grab artifacts from the new location used by
the do_deploy task.
This is the change to do_build.sh needed for https://github.com/OpenXT/xenclient-oe/pull/1341

do_build.sh: Grab deployed artifacts

---

windows/BuildSupport/winbuild-utils.ps1
windows/PackageLibrary.psm1

- The version of WIX used by the script is no longer available, upgrade to 3.11 and amend the installation steps accordingly.
- SSCE source also needs a refresh.
- Remove re-declared variables from `winbuild-prepare.ps1`.

windows: Amend preparation and build scripts

---

setup_build

`local git=${!git_var}` is a bash-ism, so specify bash as the
interpreter.

setup_build: Use bash shebang
