OpenXT/openxt

github/list_open_pull_requests.sh
originally started by @rossphilipson.
you'll need jq and a github token.
=> add a script to list the open pull requests from all the repositories

pkg-xctools/centos/xblanker, pkg-xctools/centos/xenstore-agent, pkg-xctools/control/postinst, pkg-xctools/data/etc/init.d/xblanker, pkg-xctools/data/etc/init.d/xenstore-agent, pkg-xctools/install.sh, pkg-xctools/xc-tools.spec
These are the various scripts and install files that
are used to make the pv linux tools packages.
OXT-231
=> Rebase PV Linux driver on standard PVOPS kernel/xenbus.

do_build.sh
Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>
=> fix debian_repo_xctools

do_build.sh
Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>
=> [do_build.sh] allow XC_TOOLS_BUILD to be set in .config

github/list_teams.sh
=> [github] new script to list teams

pkg-xctools/README, pkg-xctools/build.sh, pkg-xctools/control/postinst, pkg-xctools/control/prerm
=> [dkms] Move xenmou DKMS package - build and package modifications.

windows/PackageLibrary.psm1
- Cygin hash is now corrected
- The Script will now find the correct download link for Wix3.8 by
parsing the html page for its build number.
-The download link seemed to change weekly so I made it slightly dynamic
Signed-off-by: Tyler Carper tyler.carper@altamiracorp.com
=> Fixed Windows Tools Setup Script

do_build.sh
Logs *for the whole build tree* are collected after building each images, wasting a lot of time and a bit of disk space. Fix this by collecting logs just once in the ship step.
=> [do_build.sh] collect build logs only once, at the end of the build

build/conf/local.conf-dist
Signed-off-by: Chris Rogers <rogersc@ainfosec.com>
=> Dynamically determine the rootfs sizes during build time.

do_build.sh
=> do_build.sh: re-enable package tree hardlinks, saving ~1.5GB per build

pkg-xctools/README, pkg-xctools/build.sh, pkg-xctools/control/postinst, pkg-xctools/control/prerm
=> [vusb] Install Linux PV USB driver by default in debs/rpms.

pkg-xctools/control/control
=> xctools: fix the linux-headers dependency to resolve on Jessie

build/conf/local.conf-dist
OXT-308
See https://github.com/OpenXT/openxt/pull/61
=> Push configuration data into recipes

build/conf/bblayers.conf, do_build.sh, setup_build
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>
=> do_build: drop support for arbitrary extra repository

build/conf/local.conf-dist
OXT-455
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>
=> local.conf-dist: inherit xenclient-customtask

setup_build
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>
=> setup_build: use github urls for bitbake/oe-core/meta-oe

version
=> Update the version number to 5

version
=> Update master version to 6.0.0 after branching 5.x

version
=> Bump the version to 4.0.1, since 4.0.0 was released

version
=> Bump the version to 5.0.1, since 5.0.0 was released

build-scripts/build.sh, build-scripts/centos/build.sh, build-scripts/debian/build.sh, build-scripts/oe/build.sh
This is hard to test right now, since we only have one jethro-based at the moment (master)...
But it should be pretty straight forward and safe to merge.
=> build-scripts: support building a different branch

build-scripts/oe/build.sh
Fixes OXT-494
Signed-off-by: Christopher Clark <christopher.w.clark@gmail.com>
=> [build-scripts] Fix to allow an interrupted oe build to continue.

build-scripts/centos/setup.sh, build-scripts/debian/setup.sh, build-scripts/oe/setup.sh, build-scripts/setup.sh
=> build-scripts: fix user ID on known_hosts files inside the containers

build-scripts/build.sh, build-scripts/setup.sh
=> build-scripts: add proper options and add one for the git root path

github/list_open_pull_requests.sh
=> github: list_open_pull_requests.sh: show slashes in PR titles

windows/BuildDaemon/callit.sh, windows/BuildDaemon/winbuild.cfg, windows/BuildDaemon/winbuildd.py, windows/BuildDaemon/xmlhello, windows/BuildDaemon/xmlsample
Mostly working, there are still some known issues with the rsync steps.
OXT-507
=> [winbuild] Add winbuildd.py simple RPC server.

windows/BuildDaemon/winbuildd.py
=> Winbuildd fixes

github/commit_to_pull_request.sh, github/list_merges.sh, github/list_open_pull_requests.sh, github/list_repos.sh, github/list_teams.sh, github/release.sh
=> github scripts: fix the token URL in comments

windows/BuildDaemon/winbuildd.py
=> build daemon: fix logging

build-scripts/build.sh, build-scripts/setup.sh
Autostart containers and add more help to setup.sh
OXT-507
=> Build scripts improvements

build-scripts/windows/setup.sh
=> build-scripts: windows: deal with failure and move to a better location

github/pr_merger.sh
=> add a github script to merge pull requests locally

windows/makecert.bat, windows/mkbuildserver.ps1
=> Couple of small mkbuildserver improvements

windows/PackageLibrary.psm1, windows/PerformDownload.psm1, windows/mkbuildmachine.ps1
=> windows: mkbuildmachine: add support for using a mirror

github/list_open_pull_requests.sh
=> github: add users and total to list_open_pull_requests.sh

windows/PerformDownload.psm1
=> windows: mkbuildmachine: unbreak

build-scripts/setup.sh
=> build-scripts: fix owner on fetch.sh

sync-xt/common.inc
=> sync-xt: fix RPM spec files

build-scripts/build.sh, build-scripts/setup.sh, build-scripts/windows/build.sh, build-scripts/windows/setup.sh, build-scripts/windows/xmls/xml_get_ssh_public_key, build-scripts/windows/xmls/xmlbuild, build-scripts/windows/xmls/xmlgetcert, build-scripts/windows/xmls/xmlhello, windows/BuildDaemon/winbuildd.py, windows/mkbuildserver.ps1
=> windows: automate build

github/clone_organization.sh
=> [github] Add a script to clone an entire organization

build-scripts/centos/build.sh, build-scripts/debian/build.sh, build-scripts/windows/setup.sh
=> build-scripts: use the git mirror for building Debian and Centos tools

build-scripts/build.sh
=> build-scripts: fix build suffix

build-scripts/build.sh, build-scripts/windows/setup.sh, windows/BuildDaemon/start.ps1, windows/BuildDaemon/winbuildd.ps1, windows/mkbuildmachine.ps1
=> build-scripts: windows: minor fixes

build-scripts/windows/setup.sh, windows/mkbuildmachine.ps1
=> build-scripts: windows: minor instructions fix

build-scripts/setup.sh, build-scripts/windows/setup.sh
And move some code around in setup.sh
OXT-507
=> build-scripts: handle virt-install errors

do_build.sh
=> do_build.sh: remove unused steps and trailing whitespace

do_build.sh
=> acms: add skylake ACM

do_build.sh, example-config
Also remove the whole hardlink business, which doesn't make sense anymore.
OXT-546
=> do_build.sh: fix packages_tree

do_build.sh
=> do_build.sh: fix xenclient-extra name

pkg-xctools/README, pkg-xctools/build.sh, pkg-xctools/control/postinst, pkg-xctools/control/prerm
=> Remove packaging of the PV Linux audio drivers in the old scripts.

github/list_open_pull_requests.sh
=> github scripts: list_openxt_pull_requests: narrower and moar info

github/list_open_pull_requests.sh
=> github scripts: add missing element in the PR list

do_build.sh
=> do_build.sh: ignore missing sdk.zip

windows/PackageLibrary.psm1
Cygwin installer (setup-x86) does not use system proxy settings and
requires the use of the -p flag explicitly.
OXT-55
=> Use system proxy for Cygwin

windows/BuildSupport/winbuild-stage.ps1
=> windows: add -input-charset to genisoimage to remove a warning

windows/BuildSupport/winbuild-stage.ps1
=> windows: make genisoimage quiet

example-config
=> STABLE-6: Freeze openembedded-core to a specific commit

build/conf/local.conf-dist
=> local.conf-dist: prefer OpenSSL provider

version
=> Bump the version to 7.0.0 after branching 6.x

do_build.sh
(cherry picked from commit 45225b8f905d8c3dd824c1f93f8a7c07bb39ff3c)
=> STABLE-6: do_build.sh: get rid of $ORIGIN_BRANCH, just use $BRANCH

setup_build-next.sh
also clone quietly
OXT-574
(cherry picked from commit d950c680d6286481a2c2cc1337aac5eb1deb1bca)
=> STABLE-6: setup_build-next.sh: allow all layers to have a specific tag

example-config
=> STABLE-6: .config fixup for stable-6

.gitmodules, build-scripts/oe/build.sh
=> build-scripts: Fix submodules and typo

windows/BuildDaemon/start.ps1, windows/PackageLibrary.psm1, windows/PerformDownload.psm1, windows/inspectbuildmachine.ps1, windows/mkbuildmachine.ps1, windows/mkbuildserver.ps1, windows/winbuild-all.ps1, windows/winbuild-prepare.ps1
=> windows: add the MIT license header to the scripts

github/list_open_pull_requests.sh
=> list_open_pull_requests.sh: add branch label in non-short output

build-scripts/setup.sh
Add additional packages that are required for a working environment
and removed duplicate packages from list.
Signed-off-by: Daniel P. Smith <dpsmith@apertussolutions.com>
=> Cleanup package install per OXT-692

common-config, pkg-xctools/build.sh
=> [xen-4.6] Use Xen 4.6 in OpenXT

version
=> STABLE-5: Allow upgrade from OpenXT 4.0.0

version
=> [upgrade] STABLE-6 Set upgradable from version 5.0.1

version
=> [upgrade] Make 7.0.0 (master) upgradeable from 6.0.0

version
=> [upgrade] STABLE-5: Bump upgradable from to 4.0.1

build-scripts/01-xenclient-oe.layer, build-scripts/build.sh, build-scripts/oe/build.sh, do_build.sh
=> build-scripts: add modular layer support and move xenclient-oe to one

build-scripts/setup.sh
=> build-scripts: setup.sh: copy the layer files too

.gitignore, .gitmodules, setup_build-next.sh
This PR should enable building stable-6 using the very last build scripts in master.
=> STABLE-6: Add git submodules to be compatible with the new build scripts

build-scripts/oe/build.sh
=> [build] Only rsync microcode file if it exists.

build-scripts/centos/setup.sh
=> build-scripts: centos: fix slow login and tty-less builds

build-scripts/oe/setup.sh
=> [build] Add screen to OE packages to make devshell work.

build-scripts/oe/build.sh
=> build-scripts: fix downloads and cache location

build-scripts/oe/build.sh
The tabs were causing the build to beep.
=> [build-scripts] trivial improvements

version
=> STABLE-6: Bump version

build-scripts/oe/setup.sh
=> [build] Add bash-completion package, rather useful in the OE container.

build-scripts/clean.sh, build-scripts/setup.sh
=> [build] Add cleanup script.

build-scripts/build.sh
=> build-scripts: don't force an ssh tty on build

pkg-xctools/control/postinst
=> xctools: fix v4v headers installation

version
=> [Upgrade] Use wildcard 6.0.* upgradeable versions.

github/pr_merger.sh
=> github scripts: pr_merger: allow merging only 1 PR and be quieter

build-scripts/setup.sh
=> build-scripts: setup: fix container existence check

example-config
=> STABLE-6: Bump OE Jethro branches to latest, 1/2017

build-scripts/01-xenclient-oe.layer, build-scripts/oe/build.sh
=> build-scripts: layers: do not force git URLs, use the mirror by default

build-scripts/oe/build.sh
=> build-scripts: add missing step for the extra packages

build-scripts/build.sh
=> build-scripts: fix netboot directory

common-config
=> OXT-877: update xen to latest micro-release.

do_build.sh
Signed-off-by: Richard Turner <turnerr@ainfosec.com>
See OXT-887
=> Add kabylake support to our build

build-scripts/01-xenclient-oe.layer
=> build-scripts: build all the dom0 images together

build/conf/bblayers.conf
=> bblayers.conf: remove xenclient-oe, added later by the layer

build-scripts/centos/build.sh
=> build-scripts: centos: build libv4v

build-scripts/07-meta-openxt-ocaml-platform.layer
Signed-off-by: Christopher Clark christopher.clark6@baesystems.com
=> OXT-792 : add meta-openxt-ocaml-platform layer definition file

do_build.sh, example-config, setup_build, setup_build-next.sh
Just in case someone has a legacy builder using the deprecated do_build script.
=> do_build: add haskell & ocaml layers.

build-scripts/05-meta-openxt-haskell-platform.layer, build-scripts/07-meta-openxt-ocaml-platform.layer, build-scripts/20-xenclient-oe.layer
=> build-scripts: fix layer files for order and build overrides

.gitmodules, build/conf/bblayers.conf
Please see corresponding PR: https://github.com/OpenXT/xenclient-oe/pull/567
Initialized at jethro.
=> OXT-981 : introduce meta-virtualization layer

build-scripts/oe/setup.sh
=> OXT-994: add integrity checks for build tool downloads

build-scripts/build.sh, build-scripts/setup.sh
=> OXT-993: Build using layer data, version and scripts from the branch being built instead of a static copy

version
=> Bump version after stable-7 branch

build/conf/local.conf-dist
(cherry picked from commit 97edcd6a4aacf882f2ea0cded9693acedcb0db3b)
=> STABLE-7 : OXT-1016: export OCaml variables for the ocaml findlib wrapper

common-config
Upgrade common-config to use the latest Xen micro release.
=> OXT-1094: config: Xen 4.6.5 micro-upgrade

common-config
Upgrade common-config to use the latest Xen micro release.
=> STABLE-7: OXT-1094: config: Xen 4.6.5 micro-upgrade

build-scripts/build.sh, build-scripts/centos/install.sh, build-scripts/debian/install.sh
OXT-702
(cherry picked from commit a405325a0ab34934cb554964c7b0303669ec61d2)
=> STABLE-7: build-scripts: add Linux tools install scripts

build-scripts/build.sh, build-scripts/centos/install.sh, build-scripts/debian/install.sh
=> build-scripts: add Linux tools install scripts

version
=> Make master/8.0.x upgradeable from itself and 7.0.x

build-scripts/centos/setup.sh, build-scripts/debian/setup.sh, build-scripts/oe/setup.sh, build-scripts/setup.sh
=> build-scripts: add Debian Stretch host support

windows/BuildDaemon/winbuildd.py
=> winbuildd: add missing prepare parameter

common-config
=> xen: update tarball URL

common-config
(cherry picked from commit 55da11c5f25f77dd30b7512f5c5cffe21ba6dbc9)
=> STABLE-7: xen: update tarball URL

windows/BuildDaemon/winbuildd.py
(cherry picked from commit 27492c0aeb9a987032a1c587e00274cf0334f957)
=> STABLE-7: winbuildd: add missing prepare parameter

common-config
=> STABLE-6: xen: update tarball URL

common-config
See release notes:
https://www.xenproject.org/downloads/xen-archives/xen-46-series/xen-466.html
=> STABLE-7: OXT-1187: xen: upgrade to 4.6.6

build-scripts/build.sh, build-scripts/fetch.sh
=> build-scripts: let fetch.sh know the branch and print the correct git refs

build-scripts/build.sh, build-scripts/fetch.sh
(cherry picked from commit 5a7a626285c0081443e90aecf01baaa79c15275e)
=> STABLE-7: build-scripts: let fetch.sh know the branch and print the correct git refs

build-scripts/debian/install.sh
=> Debian: install.sh: always allow script to run

build-scripts/debian/install.sh
(cherry picked from commit bf49a07f8b56a1775dd2ed437d8cf5a751602e3f)
=> STABLE-7: Debian: install.sh: always allow script to run

version
=> Only allow upgrades from 7.0.0

version
=> STABLE-7: Only allow upgrades from 6.0.1

build-scripts/setup.sh
=> build-scripts: setup.sh: remove bogus package

version
=> STABLE-7: Allow upgrades from 6.1.0

version
=> STABLE-6: Bump version to 6.1.0

common-config, pkg-xctools/build.sh
Reflect Xen upgrade from https://github.com/OpenXT/xenclient-oe/pull/770.
Linked to:
- https://github.com/OpenXT/toolstack/pull/31
- https://github.com/OpenXT/xenclient-oe/pull/770
=> STABLE-6: OXT-1218: Upgrade Xen to 4.6.6.

build-scripts/setup.sh
=> build-scripts: setup.sh: fix couple of bogus conditions

windows/PackageLibrary.psm1
=> Windows build machine: install 64 bits python on 64 bits machines

build-scripts/windows/setup.sh
=> build-scripts: fix Windows wiki URL and iso download

windows/PackageLibrary.psm1, windows/makecert.bat
=> build scripts: windows: remove bogus check and fix makecert.bat

build/conf/local.conf-dist
=> OXT-1248: Add optional web-certificates image feature

build/conf/local.conf-dist
(cherry picked from commit ecb051e3a821c908f2bfe2d39e32fb43675160ea)
=> STABLE-7: OXT-1248: Add optional web-certificates image feature

.gitmodules
=> STABLE-7: Freeze remote layers to prepare for release

github/pr_merger.sh
=> github: pr_merger.sh: fix typo in usage

version
=> stable-8 is branched, bump master version to 9

.gitmodules
Update to the latest revisions used.
Instruct git-submodule to keep them as it is (consistent automated
builds).
=> STABLE-8: openxt: Use fixed revisions for stable branch.

.gitmodules
Reverts OpenXT/openxt#290
This was to be submitted against stable-8, as every name implied.
=> Revert "STABLE-8: openxt: Use fixed revisions for stable branch."

build-scripts/build.sh
=> build-scripts: fixes for re-running a finished build

build-scripts/build.sh
(cherry picked from commit 8f6c38af8c235ba1373b8d418e8b2064c3f31f6a)
=> STABLE-8: build-scripts: fixes for re-running a finished build

common-config
https://www.xenproject.org/downloads/xen-archives/xen-project-49-series/xen-492.html
=> STABLE-8: OXT-1305: xen: Upgrade to Xen 4.9.2.

build-scripts/centos/build.sh, build-scripts/debian/build.sh
Use https://github.com/OpenXT/v4v to build guest tools.
Minor changes are required with OXT-1322.
=> OXT-251, OXT-1322: Cleanup and repository synchronisation.

build-scripts/centos/build.sh, build-scripts/debian/build.sh
Stable-8 version of https://github.com/OpenXT/openxt/pull/304.
=> STABLE-8: OXT-251, OXT-1322: Cleanup and repository synchronisation.

build-scripts/setup.sh
=> Build-scripts add needed dependency mtools

build-scripts/setup.sh
(cherry picked from commit 6ef43b2bbe34be2b3c4fec9642de7c028ee64307)
Signed-off-by: Tim <tim.openxt@gmail.com>
=> STABLE-8: Build-scripts add needed dependency mtools

build-scripts/20-xenclient-oe.layer, build-scripts/build.sh, do_build.sh, manifest
Theses are the changes to build and package HVM NDMVs.
I've tested the do_build.sh changes.  The build-scripts changes, https://github.com/OpenXT/openxt/commit/29cf3fc6eb9931c6fed3a93777e6a71e395e4187, are untested, so review and test is appreciated.
Depends:
https://github.com/OpenXT/xenclient-oe/pull/912
https://github.com/OpenXT/xsm-policy/pull/20
https://github.com/OpenXT/manager/pull/116
=> OXT-1327: HVM NDVM

build-scripts/oe/build.sh
=> build-scripts: log collection: fix globbing overflow

build-scripts/oe/build.sh
OXT-1375
(cherry picked from commit 3410f2dbd32605e90c5311e2ed1f6e6937ef4312)
=> STABLE-8: build-scripts: log collection: fix globbing overflow

build/conf/local.conf-dist
=> ltrace: add new URL to MIRRORS

build/conf/local.conf-dist
(cherry picked from commit eea107989219be9b6ac62c42e4292a3c085fffef)
=> STABLE-8: ltrace: add new URL to MIRRORS

build-scripts/setup.sh
Package name was misspelled in #322
=> Fix librpmbuild package name

version
Amend the version number of the previous release.
=> version: Bump version number to 8.0.1.

build-scripts/debian/install.sh
Also fix v4v uninstall.
OXT-1348
=> debian_install.sh: fix install on non-systemd (wheezy)

.gitmodules
=> STABLE-9: Freeze all remote layers in stable-9

version
=> STABLE-9: Allow upgrade from 8.0.1 and 8.0.2 to 9.0.0, at least for now

github/clone_organization.sh, github/commit_to_pull_request.sh, github/list_merges.sh, github/list_open_pull_requests.sh, github/list_repos.sh, github/list_teams.sh, github/pr_merger.sh, github/release.sh
Allow the token to be read from a file instead of expecting the raw
value to be pasted as argument.
=> github: Try to read token from file.

do_build.sh, manifest
OXT-1539
Signed-off-by: Chris Rogers <rogersc@ainfosec.com>
=> STABLE-9: [upgrade] Add extra image step for update compat

build-scripts/20-xenclient-oe.layer, build-scripts/build.sh
=> STABLE-9: build-scripts: build new 32-bit upgrade compat image

build-scripts/build.sh, build-scripts/oe/build.sh, do_build.sh, manifest
=> build-scripts: remove architecture info from output files

build-scripts/build.sh, build-scripts/oe/build.sh, do_build.sh, manifest
OXT-1554
OXT-1552
(cherry picked from commit 8ad3e0ef4c181a073bb5adc920d0c39a92089453)
=> STABLE-9: build-scripts: remove architecture info from output files

version
=> version: upgrade master to v10

version
- Bump micro-version number to 9.0.1.
- Add upgrade path: 9.0.0 -> 9.0.1.
- Bump Windows tools version per comment.
=> S9: version: Bump micro-release version.

version
=> S9: Bump version from 9.0.1 to 9.0.2

build-scripts/setup.sh
=> build-scripts: setup.sh: fix librpm version for Debian Buster

.gitmodules, build/conf/bblayers.conf
Also add a couple of necessary standard layers.
=> Upgrade all the OE layers to zeus.
